# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# aliases
alias ls='ls --color=auto'
eval $(dircolors -b)
alias ll='ls -l'
alias la='ls -a'
alias lal='ls -al'
alias lr='ls -R'
alias b='cd ..'
alias die='sudo shutdown -P now'
alias rebirth='reboot'
alias now='date'
alias pac='sudo pacman -S'
alias agi='sudo apt-get install'
alias afi='sudo apt-fast install'
alias yt='youtube-dl -t'
alias wifi='sudo wifi-menu'
alias play='mpg123'
alias grep='grep --color=auto'
alias bower='noglob bower'

# init nvm
. $HOME/nvm/nvm.sh

# add heroku to PATH env variable
#export PATH=$PATH:/usr/local/heroku/bin

# add ruby gems to PATH env variable
export PATH=$PATH:$HOME/.gem/ruby/2.0.0/bin

# add ~/bin to PATH env variable
export PATH=$PATH:$HOME/bin

# github:rupa/z jump around
. ~/projects/forked/z/z.sh

#go
export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin


# man page coloring using less
man() {
    env LESS_TERMCAP_mb=$(printf "\e[1;31m") \
  LESS_TERMCAP_md=$(printf "\e[1;31m") \
  LESS_TERMCAP_me=$(printf "\e[0m") \
  LESS_TERMCAP_se=$(printf "\e[0m") \
  LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
  LESS_TERMCAP_ue=$(printf "\e[0m") \
  LESS_TERMCAP_us=$(printf "\e[1;32m") \
  man "$@"
}

# create a new dir and jump to it
md() {
  mkdir $1 ; cd $1
}

# initialize git repo and create README.md and .gitignore files
ginit() {
  repo=$1
  mkdir $repo
  cd $repo
  git init
  touch README.md
  echo "# "$repo >> README.md
  touch .gitignore
  echo "*.sublime-*" >> .gitignore
  echo "[Done] Created repository "$repo
}

function server() {
  local port="${1:-8000}"
  open "http://localhost:${port}/"
  python SimpleHTTPServer "$port"
}

# enables code syntax coloring in less, need to install source-highlight first
#export LESSOPEN="| /usr/bin/source-highlight-esc.sh %s"
#export LESS=' -R '

# start redshift, reduces eye strain by adjusting screen color temperature
# config file in ~/.config/redshift.conf
# disabling since it never exits
# redshift

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git battery)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:$HOME/.rvm/gems/ruby-2.0.0-p0/bin:$HOME/.rvm/gems/ruby-2.0.0-p0@global/bin:$HOME/.rvm/rubies/ruby-2.0.0-p0/bin:$HOME/.rvm/bin:$HOME/local/bin:$HOME/nvm/v0.8.22/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$HOME/.gem/ruby/2.0.0/bin:$HOME/bin

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export JAVA_HOME="/usr/java/jdk1.7.0_40"
alias llama='ssh git@git.sdslabs.co.in llama'
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
export GOPATH="/home/abhi/experiments/lime"
export PATH=/usr/local/share/npm/bin:$PATH
